In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
data=pd.read_excel("Online Retail.xlsx")
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
data_ger=data[data['Country']=="Germany"]
data_ger.head()     # boolean masking

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1097,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,12662.0,Germany
1098,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,12662.0,Germany
1099,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,12662.0,Germany
1100,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,12662.0,Germany
1101,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,12662.0,Germany

In [4]:
data.shape

(531495, 8)

In [5]:
data_ger.shape

(8668, 8)

In [6]:
# find association with description(item) and invoice number and the quantity for same invoice there are many items

In [7]:
df=pd.DataFrame({"Name":["sam","kane","jane","sammie","david"],"Age":[23,21,25,25,27],"Gender":["M","M","F","F","M"],"Marks":[78,65,78,89,76]})

In [8]:
df

     Name  Age Gender  Marks
0     sam   23      M     78
1    kane   21      M     65
2    jane   25      F     78
3  sammie   25      F     89
4   david   27      M     76

In [9]:
df.groupby("Gender").sum()

        Age  Marks
Gender
F        50    167
M        71    219

In [10]:
#if i need the Age summation only 
df.groupby("Gender")["Age"].sum()

Gender
F    50
M    71
Name: Age, dtype: int64

In [11]:
data_ger.groupby(["InvoiceNo","Description"]).sum()

                                               Quantity  UnitPrice  CustomerID
InvoiceNo Description
536527    3 HOOK HANGER MAGIC GARDEN                 12       1.95     12662.0
          5 HOOK HANGER MAGIC TOADSTOOL              12       1.65     12662.0
          5 HOOK HANGER RED MAGIC TOADSTOOL          12       1.65     12662.0
          ASSORTED COLOUR LIZARD SUCTION HOOK        24       0.42     12662.0
          CHILDREN'S CIRCUS PARADE MUG               12       1.65     12662.0
...                                                 ...        ...         ...
581578    SPOTTY BUNTING                              9       4.95     12713.0
          VINTAGE DONKEY TAIL GAME                    6       3.75     12713.0
          WRAP ALPHABET POSTER                       25       0.42     12713.0
          WRAP CIRCUS PARADE                         25       0.42     12713.0
          WRAP RED APPLES                            25       0.42     12713.0

[8641 rows x 3 columns]

In [12]:
data_ger.groupby(["InvoiceNo","Description"])["Quantity"].sum()

InvoiceNo  Description
536527     3 HOOK HANGER MAGIC GARDEN             12
           5 HOOK HANGER MAGIC TOADSTOOL          12
           5 HOOK HANGER RED MAGIC TOADSTOOL      12
           ASSORTED COLOUR LIZARD SUCTION HOOK    24
           CHILDREN'S CIRCUS PARADE MUG           12
                                                  ..
581578     SPOTTY BUNTING                          9
           VINTAGE DONKEY TAIL GAME                6
           WRAP ALPHABET POSTER                   25
           WRAP CIRCUS PARADE                     25
           WRAP RED APPLES                        25
Name: Quantity, Length: 8641, dtype: int64

In [13]:
data_ger.groupby(["InvoiceNo","Description"])["Quantity"].sum().unstack()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE SKULLS,...,YULETIDE IMAGES GIFT WRAP SET,ZINC HEART T-LIGHT HOLDER,ZINC STAR T-LIGHT HOLDER,ZINC BOX SIGN HOME,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#NAN -missing data

In [15]:
bkt=data_ger.groupby(["InvoiceNo","Description"])["Quantity"].sum().unstack().fillna(0)
bkt

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE SKULLS,...,YULETIDE IMAGES GIFT WRAP SET,ZINC HEART T-LIGHT HOLDER,ZINC STAR T-LIGHT HOLDER,ZINC BOX SIGN HOME,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536840,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581266,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581494,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581578,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bkt=bkt.astype(int)

In [17]:
# function to quantity available 
def encode_units(x):
  if x>=1:
    return 1 
  else:
    return 0

In [18]:
bkt=bkt.applymap(encode_units)

In [22]:
ap_results=apriori(bkt,min_support=0.05,use_colnames=True)
ap_results

     support                                           itemsets
0   0.104677                           (6 RIBBONS RUSTIC CHARM)
1   0.071269                        (ALARM CLOCK BAKELIKE PINK)
2   0.066815                      (CHARLOTTE BAG APPLES DESIGN)
3   0.051225                     (CHILDRENS CUTLERY DOLLY GIRL)
4   0.062361                         (COFFEE MUG APPLES DESIGN)
5   0.064588                       (FAWN BLUE HOT WATER BOTTLE)
6   0.073497                                (GUMBALL COAT RACK)
7   0.057906                             (IVORY KITCHEN SCALES)
8   0.064588                            (JAM JAR WITH PINK LID)
9   0.093541                           (JAM MAKING SET PRINTED)
10  0.062361                                 (JUMBO BAG APPLES)
11  0.080178                          (JUMBO BAG RED RETROSPOT)
12  0.102450                       (JUMBO BAG WOODLAND ANIMALS)
13  0.062361                           (LUNCH BAG APPLE DESIGN)
14  0.080178                               (LUNCH BAG WOODLAND)
15  0.064588                 (LUNCH BOX WITH CUTLERY RETROSPOT)
16  0.055679                        (MEMO BOARD COTTAGE DESIGN)
17  0.053452                              (MINT KITCHEN SCALES)
18  0.062361                 (PACK OF 20 NAPKINS PANTRY DESIGN)
19  0.060134                    (PACK OF 20 NAPKINS RED APPLES)
20  0.086860                  (PACK OF 72 RETROSPOT CAKE CASES)
21  0.118040                    (PLASTERS IN TIN CIRCUS PARADE)
22  0.109131                         (PLASTERS IN TIN SPACEBOY)
23  0.071269                        (PLASTERS IN TIN STRONGMAN)
24  0.140312                 (PLASTERS IN TIN WOODLAND ANIMALS)
25  0.051225                               (RABBIT NIGHT LIGHT)
26  0.055679                               (RED KITCHEN SCALES)
27  0.071269                      (RED RETROSPOT CHARLOTTE BAG)
28  0.071269                                (RED RETROSPOT CUP)
29  0.066815                         (RED RETROSPOT MINI CASES)
30  0.097996                    (RED TOADSTOOL LED NIGHT LIGHT)
31  0.140312                         (REGENCY CAKESTAND 3 TIER)
32  0.062361                (RETROSPOT PARTY BAG + STICKER SET)
33  0.057906                  (RETROSPOT TEA SET CERAMIC 11 PC)
34  0.160356                (ROUND SNACK BOXES SET OF 4 FRUITS)
35  0.249443               (ROUND SNACK BOXES SET OF4 WOODLAND)
36  0.051225                   (SET 2 PANTRY DESIGN TEA TOWELS)
37  0.060134                 (SET OF 3 CAKE TINS PANTRY DESIGN)
38  0.071269                       (SET OF 3 REGENCY CAKE TINS)
39  0.057906               (SET OF 60 PANTRY DESIGN CAKE CASES)
40  0.057906               (SET/20 RED RETROSPOT PAPER NAPKINS)
41  0.053452                      (SET/6 RED SPOTTY PAPER CUPS)
42  0.057906                    (SET/6 RED SPOTTY PAPER PLATES)
43  0.057906                     (SKULL LUNCH BOX WITH CUTLERY)
44  0.104677                               (SPACEBOY LUNCH BOX)
45  0.053452                   (STRAWBERRY CERAMIC TRINKET BOX)
46  0.080178                (STRAWBERRY LUNCH BOX WITH CUTLERY)
47  0.053452               (WHITE SPOT RED CERAMIC DRAWER KNOB)
48  0.129176                           (WOODLAND CHARLOTTE BAG)
49  0.069042                 (WOODLAND PARTY BAG + STICKER SET)
50  0.069042  (PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...
51  0.051225  (PLASTERS IN TIN CIRCUS PARADE, ROUND SNACK BO...
52  0.057906  (PLASTERS IN TIN CIRCUS PARADE, ROUND SNACK BO...
53  0.062361  (PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...
54  0.075724  (PLASTERS IN TIN WOODLAND ANIMALS, ROUND SNACK...
55  0.060134  (RED RETROSPOT CHARLOTTE BAG, WOODLAND CHARLOT...
56  0.133630  (ROUND SNACK BOXES SET OF 4 FRUITS, ROUND SNAC...
57  0.071269  (SPACEBOY LUNCH BOX, ROUND SNACK BOXES SET OF4...
58  0.064588  (WOODLAND CHARLOTTE BAG, ROUND SNACK BOXES SET...

In [27]:
rules=association_rules(ap_results,metric="lift",min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN CIRCUS PARADE),0.140312,0.118040,0.069042,0.492063,4.168613,0.052480,1.736359
1,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN WOODLAND ANIMALS),0.118040,0.140312,0.069042,0.584906,4.168613,0.052480,2.071067
2,(PLASTERS IN TIN CIRCUS PARADE),(ROUND SNACK BOXES SET OF 4 FRUITS),0.118040,0.160356,0.051225,0.433962,2.706237,0.032296,1.483370
3,(ROUND SNACK BOXES SET OF 4 FRUITS),(PLASTERS IN TIN CIRCUS PARADE),0.160356,0.118040,0.051225,0.319444,2.706237,0.032296,1.295941
4,(PLASTERS IN TIN CIRCUS PARADE),(ROUND SNACK BOXES SET OF4 WOODLAND),0.118040,0.249443,0.057906,0.490566,1.966644,0.028462,1.473315
5,(ROUND SNACK BOXES SET OF4 WOODLAND),(PLASTERS IN TIN CIRCUS PARADE),0.249443,0.118040,0.057906,0.232143,1.966644,0.028462,1.148599
6,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN SPACEBOY),0.140312,0.109131,0.062361,0.444444,4.072562,0.047048,1.603563
7,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.109131,0.140312,0.062361,0.571429,4.072562,0.047048,2.005939
8,(PLASTERS IN TIN WOODLAND ANIMALS),(ROUND SNACK BOXES SET OF4 WOODLAND),0.140312,0.249443,0.075724,0.539683,2.163549,0.040724,1.630520
9,(ROUND SNACK BOXES SET OF4 WOODLAND),(PLASTERS IN TIN WOODLAND ANIMALS),0.249443,0.140312,0.075724,0.303571,2.163549,0.040724,1.234424
10,(RED RETROSPOT CHARLOTTE BAG),(WOODLAND CHARLOTTE BAG),0.071269,0.129176,0.060134,0.843750,6.531789,0.050927,5.573274
11,(WOODLAND CHARLOTTE BAG),(RED RETROSPOT CHARLOTTE BAG),0.129176,0.071269,0.060134,0.465517,6.531789,0.050927,1.737625
12,(ROUND SNACK BOXES SET OF 4 FRUITS),(ROUND SNACK BOXES SET OF4 WOODLAND),0.160356,0.249443,0.133630,0.833333,3.340774,0.093630,4.503341
13,(ROUND SNACK BOXES SET OF4 WOODLAND),(ROUND SNACK BOXES SET OF 4 FRUITS),0.249443,0.160356,0.133630,0.535714,3.340774,0.093630,1.808463
14,(SPACEBOY LUNCH BOX),(ROUND SNACK BOXES SET OF4 WOODLAND),0.104677,0.249443,0.071269,0.680851,2.729483,0.045159,2.351745
15,(ROUND SNACK BOXES SET OF4 WOODLAND),(SPACEBOY LUNCH BOX),0.249443,0.104677,0.071269,0.285714,2.729483,0.045159,1.253452
16,(WOODLAND CHARLOTTE BAG),(ROUND SNACK BOXES SET OF4 WOODLAND),0.129176,0.249443,0.064588,0.500000,2.004464,0.032366,1.501114
17,(ROUND SNACK BOXES SET OF4 WOODLAND),(WOODLAND CHARLOTTE BAG),0.249443,0.129176,0.064588,0.258929,2.004464,0.032366,1.175088

In [31]:
rules[(rules["lift"]>=3) & (rules["confidence"]>=0.5) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN WOODLAND ANIMALS),0.118040,0.140312,0.069042,0.584906,4.168613,0.052480,2.071067
7,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.109131,0.140312,0.062361,0.571429,4.072562,0.047048,2.005939
10,(RED RETROSPOT CHARLOTTE BAG),(WOODLAND CHARLOTTE BAG),0.071269,0.129176,0.060134,0.843750,6.531789,0.050927,5.573274
12,(ROUND SNACK BOXES SET OF 4 FRUITS),(ROUND SNACK BOXES SET OF4 WOODLAND),0.160356,0.249443,0.133630,0.833333,3.340774,0.093630,4.503341
13,(ROUND SNACK BOXES SET OF4 WOODLAND),(ROUND SNACK BOXES SET OF 4 FRUITS),0.249443,0.160356,0.133630,0.535714,3.340774,0.093630,1.808463